<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Date</th>
				<th scope="col">Time</th>
				<th scope="col">Priority</th>
				<th scope="col">Event</th>
				<th scope="col">Message</th>
				<th scope="col">IP</th>
				<th style="width: 96px;"></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->logs as $log):?>
				<tr>
					<th scope="row"><?= $log->getId();?></th>
					<td><?= $log->getTimestamp()->format('Y-m-d');?></td>
					<td><?= $log->getTimestamp()->format('H:i:s');?></td>
					<td><?= $log->getPriorityName();?></td>
					<td><?= $log->getEventName();?></td>
					<td><?= $log->getEvent()->getMessage();?></td>
					<td><?= $log->getIpAddress();?></td>
					<td></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>

<?= $this->paginationControl(
	$this->logs,
	'sliding',
	'event-log/partial/paginator.phtml',
	array(
		'route' => 'event_log'
	)
) ?>

